backend:
  name: git-gateway

local_backend:
  url: "http://localhost:3000"

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
media_library:
  name: uploadcare
  config:
    publicKey: 19f5b0fb7c66d5c433cf

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "About", name: about, widget: object, fields: [
              {label: Image, name: image, widget: image},
              {label: "Content", name: content, widget: object, fields: [
              {label: "Synopsis", name: synopsis, widget: text},
              {label: "Production", name: production, widget: text},
              {label: "Statement", name: statement, widget: text}
              ]}
              ]}
          - {label: "Cast", name: cast, widget: object, fields: [
              {label: Image, name: image, widget: image},
              {label: "Members", name: members, widget: list, fields: [
                {label: "Name", name: name, widget: string},
                {label: Image, name: image, widget: image},
                {label: "Credits", name: credits, widget: list}
              ]}]}
          - {label: Credits, name: credits, widget: object, fields: [
              {label: Image, name: image, widget: image},
              {label: BTS, name: bts, widget: list, fields: [
                {label: Caption, name: caption, widget: string},
                {label: Image, name: image, widget: image}
              ]},
                {label: Roles, name: roles, widget: list, fields: [
                  {label: Role, name: role, widget: string},
                  {label: Members, name: members, widget: list}
                ]}
            ]}
